# Generated by Django 5.1.7 on 2025-03-30 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.CharField(choices=[('AS', 'ASPIRANT'), ('RT', 'RECRUITER')], max_length=2)),
            ],
        ),
    ]
