# Generated by Django 5.1.7 on 2025-03-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('type', models.CharField(choices=[('GN', 'GINGER'), ('ML', 'MASALA'), ('GN', 'GREEN'), ('AY', 'AYURVEDIC'), ('LN', 'LEMON')], max_length=2)),
                ('description', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
    ]
