# Generated by Django 5.1.7 on 2025-03-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivarity',
            name='type',
            field=models.CharField(choices=[('GN', 'GINGER'), ('ML', 'MASALA'), ('GN', 'GREEN'), ('HB', 'HERBAL'), ('LN', 'LEMON')], max_length=2),
        ),
    ]
